---
title: "Twindemic Analaysis"
Date: "12/7/21"
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)
library(dplyr)
library(readxl)
library(haven)
library(ggplot2)
library(patchwork)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```

# Data Cleaning

Loading the COVID data from NYC Health.
```{r}
caserate_by_zip = read_csv("./data/caserate-by-modzcta.csv")
vax_by_boro_age = read_csv("./data/coverage-by-boro-age.csv")
vax_by_boro_demo = read_csv("./data/coverage-by-boro-demo.csv")
data_by_day = read_csv("./data/data-by-day.csv")
doses_by_day = read_csv("./data/doses-by-day.csv")
hosprate_by_zip = read_csv("./data/hosprate-by-modzcta.csv")
testrate_by_zip = read_csv("./data/testrate-by-modzcta.csv")
```

Loading NYC Locations Providing Seasonal Flu Vaccinations/ Emergency Department Visits and Admissions for Influenza-like Illness/ Census Selected Social Characterisics
```{r}
flu_vaxx_loc = read_csv("./data/New_York_City_Locations_Providing_Seasonal_Flu_Vaccinations.csv")
census_social = read_csv("./data/censuszip_selected_social_characterisitcs.csv")
```
